// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX2yLfqScWXxi_WNNYMC6JWNH1eQRGlHw',
    appId: '1:630357407142:web:7f2633fe4f473e8cfbcb67',
    messagingSenderId: '630357407142',
    projectId: 'validation-demo-4a72f',
    authDomain: 'validation-demo-4a72f.firebaseapp.com',
    storageBucket: 'validation-demo-4a72f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdNQa_FSON2LaXBJgF2RiLZ6_Qn2xzsRM',
    appId: '1:630357407142:android:7db543abf6ed6031fbcb67',
    messagingSenderId: '630357407142',
    projectId: 'validation-demo-4a72f',
    storageBucket: 'validation-demo-4a72f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMr4p2lPKOc2IVyMapBI3yolXRA7i17pA',
    appId: '1:630357407142:ios:506f59c0794046c5fbcb67',
    messagingSenderId: '630357407142',
    projectId: 'validation-demo-4a72f',
    storageBucket: 'validation-demo-4a72f.firebasestorage.app',
    iosBundleId: 'com.example.blocLoginValidation',
  );
}
